FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
ENV NODE_ENV=production
ENV USE_HTTPS=false
ENV HOST=0.0.0.0
ENV STRICT_PRODUCTION_GUARD=false
ENV ENABLE_APP_DB=false
ENV ENABLE_POSTGRES_STORAGE=false
ENV AUTH_REQUIRE_DATABASE_FOR_CLIENT_AUTH=false
ENV CLUSTER_MODE=false
ENV ENABLE_REDIS_RUNTIME=false
ENV ENABLE_REDIS_EVENT_QUEUE=false
ENV SMTP_ENABLED=false
EXPOSE 3443
CMD ["node", "server.js"]
